# .gitlab-ci.yml

image: golang:1.22-bullseye

build:
  parallel:
    matrix:
      - GOOS:
          - linux
          - darwin
          - windows
        GOARCH:
          - amd64
          - arm64
  artifacts:
    paths:
      - matrix/hello-${GOOS}-${GOARCH}
  script:
    - cd matrix
    - go build -o hello-${GOOS}-${GOARCH} main.go
